macro(GENERATE_PLATFORM_MACROS)
if (WIN32)
  add_compile_definitions(OS_WINN)
elseif (UNIX)
  if (NOT APPLE)
    add_compile_definitions(OS_LINUX)
  else()
    add_compile_definitions(OS_APPLE)
  endif()
endif()
endmacro()
